### ISSUE TITLE
How to get dataset

### ISSUE THREAD

**Issue by ShichaoJiao** [tianbao-li/MI3DOR#1]
I checked the website of SHREC19 and did not find the download address of the data set. At the same time, I also sent an email and did not get a response

**Comment by tianbao-li** [comment]
> I checked the website of SHREC19 and did not find the download address of the data set. At the same time, I also sent an email and did not get a response


Hi~

Sorry for the delay.

We need a senior project manager or senior researcher at your institution to sign the attached agreement (https://github.com/tianbao-li/MI3DOR/blob/main/dataset/MI3DOR_Database_Agreement.pdf) for using our dataset.

Please send the completed form to me (litianbao@tju.edu.cn) and cc to Prof. Song (dan.song@tju.edu.cn) using institutional email address. Then we will reply with the download link and password.

Thanks for your understanding.

**Comment by MrLogic1** [comment]
如何得到mi3dor2数据集的使用权限

**Comment by MrLogic1** [comment]
MI3DOR2数据集怎么得到呀
