### ISSUE TITLE
怎样得到MI3DOR2数据集的使用权限

### ISSUE THREAD

**Issue by MrLogic1** [tianbao-li/MI3DOR#3]
如何得到MI3DOR2数据集的使用权限

**Comment by tianbao-li** [comment]
你好，你在这里留个邮箱，或者给我发个邮件(litianbao@tju.edu.cn)，我先发你一份MI3DOR-2的数据集，等我们整理后会公布在本GitHub项目里。

**Comment by MrLogic1** [comment]
好的不胜感激我的邮箱是17663234661@163.com

**Comment by MrLogic1** [comment]
您好，先前有在邮箱联系过，邮箱是202221100446@stu.ujn.edu.cn，再次感谢您的帮助

**Comment by MrLogic1** [comment]
好的，谢谢回复，我的邮箱是dzy10242023@163.com
